# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("9.0.0")


configfile: "config/config.yaml"


pepfile: config["pepfile"]


report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/host_filtering.smk"
include: "rules/assembly.smk"
include: "rules/metabat.smk"
include: "rules/metacoag.smk"
include: "rules/das_tool.smk"
include: "rules/bin_qc.smk"
include: "rules/classify.smk"
include: "rules/analysis.smk"
include: "rules/report.smk"


rule all:
    input:
        # read classification output
        expand(
            "results/{project}/output/classification/reads/{sample}/{sample}_{level}_kaiju_summary.tsv",
            project=get_project(),
            sample=get_samples(),
            level=["species", "genus", "family", "order", "class", "phylum"],
        ),
        # binning summary output
        expand(
            "results/{project}/output/report/{sample}/{sample}_DASTool_summary.tsv",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/proteins/{sample}/{sample}_proteins.faa.gz",
            project=get_project(),
            sample=get_samples(),
        ),
        # fasta output
        expand(
            "results/{project}/output/fastas/{sample}/bins/",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/fastas/{sample}/mags/",
            project=get_project(),
            sample=get_samples(),
        ),
        # plasmid analysis
        expand(
            "results/{project}/output/plasmids/{sample}/{sample}_plasmid_summary.tsv",
            project=get_project(),
            sample=get_samples(),
        ),
        # overall report
        expand(
            "results/{project}/output/report/report_{project}.zip",
            project=get_project(),
        ),
        # resistance analysis
        expand(
            "results/{project}/output/resistance/CARD/reads/{sample}/{sample}.gene_mapping_data.txt",
            project=get_project(),
            sample=get_samples(),
        ),
