# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("9.0.0")

containerized: "containerization/my_container.sif"

configfile: "config/config.yaml"


pepfile: config["pepfile"]


report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/host_filtering.smk"
include: "rules/assembly.smk"
include: "rules/metabat.smk"
include: "rules/metacoag.smk"
include: "rules/das_tool.smk"
include: "rules/bin_qc.smk"
include: "rules/classify.smk"
include: "rules/analysis.smk"
include: "rules/resistance.smk"


rule all:
    input:
        expand("results/{project}/output/report/multiqc_{project}.html",project=get_project()),
        # 2. Species diversity
        expand("results/{project}/output/report/{sample}/{sample}_summary_quality.csv",project=get_project(),sample=get_samples(),),
        # 3. Assembly results
        expand("results/{project}/output/report/{sample}/{sample}_summary_assembly.csv",project=get_project(),sample=get_samples(),),
        # 5. Taxonomic classification
        expand(
            "results/{project}/output/report/{sample}/{sample}_kaiju_krona_reads.html",
            project=get_project(),sample=get_samples(),
        ),
        expand(
            "results/{project}/output/report/{sample}/{sample}_kaiju_krona_contigs.html",
            project=get_project(),sample=get_samples(),
        ),
        # fasta output
        expand(
            "results/{project}/output/fastas/{sample}/bins/",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/fastas/{sample}/mags/",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/classification/bins/{sample}/{sample}_{stage}_abundance.csv",
            project=get_project(),
            sample=get_samples(),
            stage=['bins','mags']
        ),
        expand(
            "results/{project}/output/classification/reads/{sample}/{sample}_reads_{level}_abundance.csv",
            project=get_project(),
            sample=get_samples(),
            level=["species", "genus", "family", "order", "class", "phylum"],
        ),
        expand(
            "results/{project}/output/classification/assembly/{sample}/{sample}_assembly_{level}_abundance.csv",
            project=get_project(),
            sample=get_samples(),
            level=["species", "genus"],
        ),
        # plasmid analysis
        expand(
            "results/{project}/output/plasmids/{sample}/{sample}_plasmid_summary.tsv",
            project=get_project(),
            sample=get_samples(),
        ),
        # resistance analysis
        expand(
            "results/{project}/output/resistance/CARD/reads/{sample}/{sample}.gene_mapping_data.txt",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/resistance/uniCARD/per_sample_resistance_abundance/{sample}_drug_class_abundance.csv",
            project=get_project(),sample=get_samples(),
        ),
        #contig classification
        expand(
            "results/{project}/output/classification/assembly/{sample}/kaiju.out.gz",
            project=get_project(),
            sample=get_samples(),
        ),

'''# read classification output
        expand(
            "results/{project}/output/classification/reads/{sample}/{sample}_{level}_abundance.tsv",
            project=get_project(),
            sample=get_samples(),
            level=["species", "genus", "family", "order", "class", "phylum"],
        ),'''


PROJECT=get_project()

onsuccess:
    print("Pipeline finished without an error. Cleaning all temporary folders: ")
    shell("bash workflow/scripts/cleanup_intermediate.sh results/{PROJECT}")

onerror:
    print("An error occurred while running the pipeline. Clean up of temporary files will be skipped.")