# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

from snakemake.utils import min_version

min_version("9.0.0")

containerized: "containerization/my_container.sif"

configfile: "config/config.yaml"


pepfile: config["pepfile"]


report: "report/workflow.rst"


include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/host_filtering.smk"
include: "rules/assembly.smk"
include: "rules/metabat.smk"
include: "rules/metacoag.smk"
include: "rules/das_tool.smk"
include: "rules/bin_qc.smk"
include: "rules/classify.smk"
include: "rules/analysis.smk"
include: "rules/resistance.smk"
#include: "rules/report.smk"

report_input = list()
if config["host-filtering"]["do-host-filtering"]:
    report_input.append("results/{project}/output/report/host_filtering/")


rule all:
    input:
        report_input,
        expand("results/{project}/output/report/all/multiqc_{project}.html",project=get_project()),
        # 2. Species diversity
        expand("results/{project}/output/report/all/quality_summary/",project=get_project()),
        # 3. Assembly results
        expand("results/{project}/output/report/all/assembly/",project=get_project()),
        expand(
            "results/{project}/output/report/{sample}/bin/",
            project=get_project(),sample=get_samples(),
        ),
        expand(
            "results/{project}/output/report/{sample}/taxonomy/",
            project=get_project(),sample=get_samples(),
        ),
        # 5. Taxonomic classification
        expand(
            "results/{project}/output/report/{sample}/mags/",
            project=get_project(),sample=get_samples(),
        ),
        expand(
            "results/{project}/output/report/{sample}/{sample}_reads_kaiju.out.html",
            project=get_project(),sample=get_samples(),
        ),
        expand(
            "results/{project}/output/report/{sample}/{sample}_contigs_kaiju.out.html",
            project=get_project(),sample=get_samples(),
        ),
        # read classification output
        expand(
            "results/{project}/output/classification/reads/{sample}/{sample}_{level}_abundance.tsv",
            project=get_project(),
            sample=get_samples(),
            level=["species", "genus", "family", "order", "class", "phylum"],
        ),
        # binning summary output
        expand(
            "results/{project}/output/report/{sample}/{sample}_DASTool_summary.tsv",
            project=get_project(),
            sample=get_samples(),
        ),
        # fasta output
        expand(
            "results/{project}/output/fastas/{sample}/bins/",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/fastas/{sample}/mags/",
            project=get_project(),
            sample=get_samples(),
        ),
        # plasmid analysis
        expand(
            "results/{project}/output/plasmids/{sample}/{sample}_plasmid_summary.tsv",
            project=get_project(),
            sample=get_samples(),
        ),
        # resistance analysis
        expand(
            "results/{project}/output/resistance/CARD/reads/{sample}/{sample}.gene_mapping_data.txt",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/output/resistance/uniCARD/{project}_drug_class_abundance_all_possible.csv",
            project=get_project(),
        ),
        #contig classification
        expand(
            "results/{project}/output/classification/assembly/{sample}/kaiju.out.gz",
            project=get_project(),
            sample=get_samples(),
        ),
        #cleanup
        expand(
            "results/{project}/cleanup/{sample}_fastp.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_fastq.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_human_map.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_kaiju_reads.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_kaiju_contigs.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_gtdb.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_unicard.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_assembly.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_proteins.done",
            project=get_project(),
            sample=get_samples(),
        ),
        expand(
            "results/{project}/cleanup/{sample}_dastool.done",
            project=get_project(),
            sample=get_samples(),
        ),


'''# overall report
        expand(
            "results/{project}/output/report/report_{project}.zip",
            project=get_project(),
        ),'''