pepfile: config/pep/config.yaml

## Please change to a name describing your project
## All results can be found under results/project-name/
project-name: "test"

quality-criteria:
  # minimal length of acceptable reads
  min-length-reads: 30
  # average quality of acceptable reads (PHRED)
  min-PHRED: 20

adapter-seqs: "-a CTGTCTCTTATACACATCT -g AGATGTGTATAAGAGACAG"

# reads are always filtered for human contamination
human-filtering:
  # if you have a human reference genome on your device,
  # you can set use-local to True and specify the path to the human reference genome
  use-local: True
  # path to a locally stored human reference genome
  local-path: /groups/ds/databases_refGenomes/refGenomes/latest/human/GRCh38_latest_genomic.fna.gz
  # if use-local = False the reference genome is downloaded via the following url
  download-path: https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/GRCh38_latest/refseq_identifiers/GRCh38_latest_genomic.fna.gz

# if filtering for non-human host is required,
# specify a host name and the path to the reference genome
host-filtering:
  do-host-filtering: False
  #e.g.: pig
  host-name:
  #e.g.: resources/ref_genome/GCF_000003025.6_Sscrofa11.1_genomic.fa.gz
  ref-genome:

# minimum contig length used during assembly step
min-contig-length: 300

MAG-criteria:
  min-completeness: 50.00
  max-contamination: 30.00

### Handling of different databases
## The GTDB has about 140 Gb
# please specify the folder where the decompressed database is stored
gtdb: /groups/ds/databases_refGenomes/databases/latest/gtdb/release226/

kaiju:
  use-local: True
  # path of kaiju DB .fmi file
  # if use-local False: DB is downloaded and saved to this path
  fmi-file: /groups/ds/databases_refGenomes/databases/latest/kaiju/refseq_nr/unpacked_2024-08-13/kaiju_db_refseq_nr.fmi
  download: https://kaiju-idx.s3.eu-central-1.amazonaws.com/2024/kaiju_db_refseq_nr_2024-08-13.tgz

checkm2:
  use-local: True
  #if use-local False a folder named CheckM2_database will be created under the given path
  db-folder: /groups/ds/databases_refGenomes/databases/latest/checkM2/

# folder of genomad DB
genomad:
  use-local: True
  # a folder named genomad_db is expected under the given path
  # if use-local False this folder will be created
  db-folder: /groups/ds/databases_refGenomes/databases/latest/

card:
  use-local: True
  db-file: /groups/ds/databases_refGenomes/databases/latest/card/card.json
  version: v4.0.1
  url: https://card.mcmaster.ca/latest/data

uniCARD:
  #path to the .dmnd file of UniCARD database
  db-file: /groups/ds/databases_refGenomes/databases/latest/uniCARD/uniCARD.dmnd
  # path to CARDs hierarchy file
  hierarchy-json: /groups/ds/databases_refGenomes/databases/latest/uniCARD/CARD_hierarchy_v4.0.0.json

## string term used for formatting output tables
tablular-config: '/>github<\/a>/a \\t\t\t</li>\n\t\t\t<li class="nav-item"> \n\t\t\t\t<a class="nav-link" href="#">'

# If testing set true
testing: False
